import Head from 'next/head'
import { useState, createContext } from 'react'
import '../styles/globals.scss'
import type { AppProps } from 'next/app'
import { Dispatch, SetStateAction } from 'react'

type FilterContextType = {
  filter: string
  setFilter: Dispatch<SetStateAction<string>>
}

export const FilterContext = createContext<FilterContextType>({filter: '', setFilter: () => {}})

function MyApp({ Component, pageProps }: AppProps) {
  const [state, setState] = useState('')
  return (
    <>
      <Head>
        <title>Desafio Linx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FilterContext.Provider value={{filter: state, setFilter: setState}}>
        <Component {...pageProps} />
      </FilterContext.Provider>
    </>
  )
}
export default MyApp
